;;;  -*- Package: cassandra -*-
;;;
;;; Autogenerated by Thrift
;;; DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

(cl:in-package :cassandra-8-1-0)

(thrift:def-constant "VERSION" "8.1.0")

