;;;  -*- Package: cassandra_8.3.0 -*-
;;;
;;; Autogenerated by Thrift
;;; DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

(cl:in-package :cassandra_8.3.0)

(thrift:def-constant "VERSION" "8.3.0")

