;;;  -*- Package: cassandra_2.1.0 -*-
;;;
;;; Autogenerated by Thrift
;;; DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

(cl:in-package :cassandra_2.1.0)

(thrift:def-constant "VERSION" "2.1.0")

